config/routes.rb
Rails.application.routes.draw do

  resources :missing_requests do
    member do
      post :close
    end
  end
  get 'signup'  => 'users#new'
  resources :users

  get 'login' => 'sessions#new' # метод new создает и сразу возвращает новый объект?
  post 'login' => 'sessions#create'
  post 'logout' => 'sessions#destroy'

  get 'close' => 'missing_requests'

  get 'missing_requests/:id/close' => 'session#new'

  root 'sessions#new'
end

app/models/missing_request.rb
class MissingRequest < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
	  @current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

  def require_user
    redirect_to '/login' unless current_user
  end
end

app/controllers/missing_requests_controller.rb
class MissingRequestsController < ApplicationController
  before_action :require_user
  before_action :set_missing_request, only: [:show, :edit, :update, :destroy, :close]
  # TODO: use cancan or smt like that for protect page

  # GET /missing_requests
  # GET /missing_requests.json
  def index
    @missing_requests = MissingRequest.all
  end

  # GET /missing_requests/1
  # GET /missing_requests/1.json
  def show
  end

  # GET /missing_requests/new
  def new
    @missing_request = MissingRequest.new
  end

  # GET /missing_requests/1/edit
  def edit
  end

  # POST /missing_requests
  # POST /missing_requests.json
  def create
    @missing_request = MissingRequest.new(missing_request_params)
    @missing_request[:status] = false

    respond_to do |format|
      if @missing_request.save
        format.html { redirect_to @missing_request, notice: 'Missing request was successfully created.' }
        format.json { render :show, status: :created, location: @missing_request }
      else
        format.html { render :new }
        format.json { render json: @missing_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /missing_requests/1
  # PATCH/PUT /missing_requests/1.json
  def update
    respond_to do |format|
      if @missing_request.update(missing_request_params)
        format.html { redirect_to @missing_request, notice: 'Missing request was successfully updated.' }
        format.json { render :show, status: :ok, location: @missing_request }
      else
        format.html { render :edit }
        format.json { render json: @missing_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /missing_requests/1
  # DELETE /missing_requests/1.json
  def destroy
    @missing_request.destroy
    respond_to do |format|
      format.html { redirect_to missing_requests_url, notice: 'Missing request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /missing_requests/1/close
  def close
    @missing_request.update_attributes(status: true)
    redirect_to(@missing_request)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_missing_request
      @missing_request = MissingRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def missing_request_params
      params.require(:missing_request).permit(:text, :comment, :status)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to '/missing_requests'
    else
      redirect_to 'login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
  @user = User.new(user_params)
  if @user.save
    session[:user_id] = @user.id
    redirect_to '/'
  else
    redirect_to '/signup'
  end
end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/missing_requests_helper.rb
module MissingRequestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VeryImportantProgect</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/missing_requests/_form.html.erb
<%= form_for(@missing_request) do |f| %>
  <% if @missing_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@missing_request.errors.count, "error") %> prohibited this missing_request from being saved:</h2>

      <ul>
      <% @missing_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label>Текст:</label>
    <%= f.text_field :text, class: "form-control textbox" %>
  </div>

  <div class="field">
    <label>Комментарий:</label>
    <%= f.text_field :comment, class: "form-control textbox" %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "Редактировать", :class => "btn btn-primary" %>
  </div>
  <br>
<% end %>

app/views/missing_requests/edit.html.erb
<div class="panel panel-default">
  <h1>Редактировать</h1>
  <%= render 'form' %>
  <%= link_to 'Просмотреть', @missing_request, class: "btn btn-info" %>
  <%= link_to 'Назад', missing_requests_path, class: "btn btn-info back-button" %>
</div>

app/views/missing_requests/index.html.erb
<div class="panel panel-default">
  <p id="notice"><%= notice %></p>
  <h1>Запросы о пропаже</h1>
  <br>
  <table class="table table-inverse">
    <thead>
      <tr>
        <th>Текст</th>
        <th>Комментарий</th>
        <th>Статус</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @missing_requests.each do |missing_request| %>
        <tr>
          <td><%= missing_request.text %></td>
          <td><%= missing_request.comment %></td>
          <td>
            <% if missing_request.status %>
              Закрыто
            <% else %>
              Открыто
            <% end %>
          </td>
          <td><%= link_to 'Просмотреть', missing_request %></td>
          <td><%= link_to 'Редактировать', edit_missing_request_path(missing_request) %></td>
          <td><%= link_to 'Закрыть', close_missing_request_path(missing_request), :method => :post   %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Создать', new_missing_request_path, class: "btn btn-primary" %>
</div>

app/views/missing_requests/new.html.erb
<div class="panel panel-default">
  <h1>Новый запрос о пропаже</h1>
  <%= render 'form' %>
  <%= link_to 'Назад', missing_requests_path, class: "btn btn-info" %>
<div class="panel panel-default">

app/views/missing_requests/show.html.erb
<div class="panel panel-default">
  <p id="notice"><%= notice %></p>

  <dl class="row">
    <dt class="col-sm-1">Текст:</dt>
    <dd class="col-sm-1"><%= @missing_request.text %></dd>
  </dl>

  <dl class="row">
    <dt class="col-sm-1">Комментарий:</dt>
    <dd class="col-sm-1"><%= @missing_request.comment %></dd>
  </dl>

  <dl class="row">
    <dt class="col-sm-1">Статус:</dt>
    <dd class="col-sm-1">
      <% if @missing_request.status %>
        Закрыто
      <% else %>
        Открыто
      <% end %>
    </dd>
  </dl>

  <%= link_to 'Редактировать', edit_missing_request_path(@missing_request), class: "btn btn-info" %>

  <%= link_to 'Назад', missing_requests_path, class: "btn btn-info back-button" %>
</div>

app/views/users/new.html.erb
<div class="panel panel-default register-panel">

    <h1>Регистрация</h1>
    <br>
    <%= form_for(@user) do |f| %>
      <div class="form-group">
        <%= f.text_field :name, :placeholder => "Логин", class: "form-control textbox" %>
      </div>
      <div class="form-group">
        <%= f.email_field :email, :placeholder => "EMail", class: "form-control textbox" %>
      </div>
      <div class="form-group">
        <%= f.password_field :password, :placeholder => "Пароль", class: "form-control textbox" %>
      </div>
      <%= f.submit "Зарегистрироваться", class: "btn btn-primary" %>
    <% end %>
  </div>